[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "canvas_plus"
version = "0.1.0"
requires-python = ">=3.14"
dependencies = [
    "dj-database-url>=3.1.2",
    "Django==6.1.1",
    "gunicorn>=26.2.0",
    "psycopg[binary]>=3.3.6",
]

[tool.setuptools]
packages = []

[project.optional-dependencies]
dev = [
    "pylint==4.1.1",
    "pytest==9.1.1",
    "pytest-cov==7.1.0",
    "pytest-django==4.14.0",
]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "canvas_plus.settings"
pythonpath = ["canvas_plus", "."]
python_files = ["test_*.py", "tests.py"]

[tool.coverage.run]
omit = [
    "*/manage.py",
    "*/asgi.py",
    "*/wsgi.py",
    "*/migrations/*",
    "canvas_plus/canvas_plus/settings.py"
    ]

[tool.pylint.main]
ignore = [
    ".venv",
    "migrations"
    ]

